# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main
pr:
  - main

variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTest
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make checks && make unit-test
      displayName: Run checks and unit test
    - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
      env:
        CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
      displayName: Upload coverage to Codecov
