#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "edge-core ci"

env:
  GO_VERSION: 1.17

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run checks
        run: |
          make checks

  unitTest:
    name: Unit test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: matrix.os == 'ubuntu-latest' && github.repository == 'trustbloc/sidetree-core-go'
        uses: codecov/codecov-action@v1.3.1
        with:
          file: ./coverage.txt

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=trustbloc
            -Dsonar.projectKey=trustbloc_sidetree-core-go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 82580866f1b5a5040e9d015d26bed102e7ca42f3
